// <auto-generated />
namespace JobSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class some_relationships_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(some_relationships_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201811120800297_some_relationships_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
