// <auto-generated />
namespace JobSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class jobs_corrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobs_corrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201811120739018_jobs_corrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
